In [ ]:
msg = "Hello World"
print(msg)

In [3]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:

np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:

arr = np.arange(25)
print(arr)
arr?

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


Type:            ndarray
String form:    
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Length:          25
File:            c:\users\kiran\myvirtualenvs\env1\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the _

In [8]:
def add_number(a, b):
    return a + b

print(add_number(1,3))
add_number??

4


Signature: add_number(a, b)
Docstring: <no docstring>
File:      c:\users\kiran\repos\learning_jupyter\<ipython-input-8-7acb2a89de63>
Type:      function


In [10]:
np.*load*?

np.__loader__
np.load
np.loads
np.loadtxt

In [1]:
print("Kiran")

Kiran


In [2]:
import numpy as np
sample_arr = np.arange(15)
print(sample_arr)

NameError: name 'np' is not defined

In [44]:
import numpy as np

arr = np.ndarray(shape=(7,4), dtype=float, order='F')
print("Printing the first row {}\n\n".format(arr[0]))

np.savetxt("trash.txt", arr, delimiter=",")
if os.path.isfile("trash.txt"):
    arr1 = np.loadtxt("trash.txt", delimiter=",", usecols=(0,2), skiprows=3) # use 0,2 columns and skip first 3 rows
    print(arr1)
    print(arr1.shape)
    print(arr1.dtype)
    os.remove("trash.txt")


Printing the first row [2.41907520e-312 2.56761491e-312 6.79038653e-313 2.35541533e-312]


[[2.37663529e-312 1.29441743e-312]
 [2.33419537e-312 2.29175545e-312]
 [2.05833592e-312 2.05833592e-312]
 [2.41907520e-312 9.33678149e-313]]
(4, 2)
float64


     ID    num        Date                           Address
0  4141  13021  1607472343                 831-4189 Nunc Av.
1  7946  28308  1647566662                   4692 Augue. Rd.
2  9464   3154  1611525228  P.O. Box 255, 3515 Facilisis Av.
int32


ID         float64
num          int64
Date        object
Address     object
dtype: object
ID                       1572.0
num                       99248
Date        2021-04-19 00:48:31
Address    [355-6487, Sed, St.]
Name: 0, dtype: object
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
2021-03-27 23:28:00.074252
